---

name: Workflow2

on:
  workflow_run:
    workflows: [Workflow1]
    types: [completed]
    branches: [test-branch1]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "::notice file=workflow2.yaml::starting "
          sleep 10 
          echo "::notice file=workflow2.yaml::This is step from Workflow2"
