---

name: Workflow2

on:
  workflow_run:
    workflows: [Workflow1]
    types: [completed]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo 'This is step from Workflow2'
