---

name: Workflow1
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "::notice file=workflow1.yaml::starting "
          sleep 60
          echo "::notice file=workflow1.yaml::This is step from Workflow1"
