---

name: Workflow1
on: [push, pull_request_target]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "::notice file=workflow1.yaml::starting "
          sleep 1
          echo "::notice file=workflow1.yaml::This is step from Workflow1"
          echo "::notice file=workflow1.yaml::Change from master no in PR"
          echo "::notice file=workflow1.yaml::Change2 from master not in PR, also visible in merge commit"
          # exit 1 # fail!
