---

name: Workflow4

on:
  release:
    types: [published]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "::notice file=workflow4.yaml::starting "
          sleep 10
          echo "::notice file=workflow4.yaml::This is step from Workflow4 bla2"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: checkout
        if: ${{ github.event_name == 'release' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.head_sha }}
          fetch-depth: 0
      - name: Shas
        run: |
          echo "::notice file=workflow4.yaml::release.head_sha ${{github.event.release.head.sha}}"
          echo "::notice file=workflow4.yaml::github.sha ${{github.sha}}"
