---

name: Workflow2

on:
  workflow_run:
    workflows: [Workflow1]
    types: [completed]
    branches: [test-branch1,main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "::notice file=workflow2.yaml::starting "
          sleep 1
          echo "::notice file=workflow2.yaml::This is step from Workflow2"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: checkout
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Debug
        run: |
          echo 'Test PR 2'
          cat .github/workflows/workflow2.yaml
